### ISSUE TITLE
doko-search.com not sure! (open for suggestions)

### ISSUE THREAD

**Issue by rolandinsh** [piwik/referrer-spam-blacklist#110]
found yesterday in referrer list doko-search.com. By search on internet look like unwanted adware in user computers, but referrer itself **could** be valid.

Just opened for comments from others
# Doko Search

from their web:

Doko search aims to provide the ultimate online search experience. Our advanced technology provides you with the best of what the web has to offer, and makes it easier than ever to find exactly what you are searching for. **_Doko search has partnered with some of the most popular software packages in world, giving you the option to install our search settings during setup and giving them the opportunity to offer you their products for free**_.

**Comment by spmedia** [comment]
Website seems to no longer be around. Closed.
