### ISSUE TITLE
Some more referrer spam blacklist suggestions

### ISSUE THREAD

**Issue by nekohayo** [piwik/referrer-spam-blacklist#111]
Hi there,

For some reason one of my websites is more prone to being a target for referrer spam than my other websites. I do run an outdated version of Piwik so will be upgrading soon to benefit from the updated spammers.txt, but I think I've seen some items in here that were not present in your blocklist:
Not in your list:

```
aetherwu.com
aosheng-tech.com
atmosphericwatergenerator.net
buypharmacydrug.com
compassoffices.com
make-money-online.7makemoneyonline.com
medispainstitute.com.au
moonstruck.co.za
musicas.baixar-musicas-gratis.com
musicas.kambasoft.com
screen-recorder.srecorder.com
turtleluck.com
www.barakaweb.com
www.star61.de
www.viandpet.com
youtube-downloader.savetubevideo.com
```

Not sure, but since I don't have RSS feeds on this particular website:

```
www.inoreader.com
newsblur.com
```

Already in your list:

```
best-seo-offer.com
best-seo-solution.com
break-the-chains.com
buttons-for-website.com
buttons-for-your-website.com
civilwartheater.com
semaltmedia.com
semalt.semalt.com
sharebutton.net
success-seo.com
video--production.com
videos-for-your-business.com
```

Variants of stuff you already have in your list:

```
103026.semalt.com
14.semalt.com
18.semalt.com
19.semalt.com
1.semalt.com
20.semalt.com
22.semalt.com
23.semalt.com
249.semalt.com
27.semalt.com
295.semalt.com
29.semalt.com
30.semalt.com
317.semalt.com
34.semalt.com
353.semalt.com
361.semalt.com
36381278.videos-for-your-business.com
36.semalt.com
409.semalt.com
419.semalt.com
428.semalt.com
43.semalt.com
44.semalt.com
479.semalt.com
499.semalt.com
505.semalt.com
51.semalt.com
52.kambasoft.com
54233248.semalt.com
57.semalt.com
61.kambasoft.com
63.semalt.com
643.semalt.com
65.semalt.com
696.semalt.com
74.semalt.com
750.semalt.com
766.semalt.com
76.semalt.com
78.semalt.com
7.kambasoft.com
822.semalt.com
831.semalt.com
83.semalt.com
85.semalt.com
86.semalt.com
87.semalt.com
89.semalt.com
9.semalt.com
```

**Comment by lembitk** [comment]
+1 for:

1. `aosheng-tech.com`
1. `buypharmacydrug.com`
1. `srecorder.com`
1. `star61.de`
1. `viandpet.com`

PS. These are already on the list: 

1. [`7makemoneyonline.com`](https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt#L7)
1. [`baixar-musicas-gratis.com`](https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt#L34)
1. [`kambasoft.com`](https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt#L155)
1. [`savetubevideo.com`](https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt#L224)

**Comment by mattab** [comment]
@lembitk thx for the feedback. do you mind creating a PR for all those that you have +1 today? then we can merge and close all issues at once! cheers

**Comment by lembitk** [comment]
Sure @mattab, will do. 

However, you might want to check these PR's in the meantime, as it seems to me that these would merge w/o any conflicts right now: #75, #77, #79, #89, #107, and #137.

PS. **Thanks.** I think/hope that this project has the potential to become *the* “canonical” referrer spambot list.

**Comment by mattab** [comment]
Merged these as you suggested. thanks for your contribs!

**Comment by lembitk** [comment]
Considering [5 suggested domains are confirmed](https://github.com/piwik/referrer-spam-blacklist/issues/111#issuecomment-159136866) above earlier, domains still waiting for confirmation are: 

1. `aetherwu.com`
1. `atmosphericwatergenerator.net`
1. `barakaweb.com`
1. `compassoffices.com`
1. `inoreader.com`
1. `medispainstitute.com.au`
1. `moonstruck.co.za`
1. `newsblur.com`
1. `turtleluck.com`

**Comment by DCI-7** [comment]
с.новым.годом.рф
hits me pretty often

**Comment by lembitk** [comment]
@DCI-7: please note that [`годом.рф` is already on the list](https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt#L329).
