### ISSUE TITLE
Add qualitymarketzone.com

### ISSUE THREAD

**Issue by chrisblakley** [piwik/referrer-spam-blacklist#112]
Just started showing up today in my referrals.

```
qualitymarketzone.com
```

**Comment by appeltauer** [comment]
+1 On multiple sites and digmato.com is already uploading GA filters update with this domain.
It's affiliate, so clearly a spammer.

**Comment by mnapoli** [comment]
Thanks for confirming, seems legit indeed. Even visiting the website redirects to `click.aliexpress.com` which is blocked by ublock.

Will add it to the list.
