### ISSUE TITLE
Spam Suggestion

### ISSUE THREAD

**Issue by AreliGroup** [piwik/referrer-spam-blacklist#125]
I'm not sure if it was mentioned, but I've been seeing t.co recently.

**Comment by kfinley** [comment]
t.co is not spam. That's Twitter's short URL domain. This should not be blocked.

**Comment by mnapoli** [comment]
Indeed: https://support.twitter.com/articles/196940

**Comment by AreliGroup** [comment]
Oh wow, great. Thank you for letting me know!
