### ISSUE TITLE
bing.com, symbaloo

### ISSUE THREAD

**Issue by brynnd** [piwik/referrer-spam-blacklist#126]
Hello,
I've received a referred website:  bing.com.  It appears to be a search engine.  I've read the instructions for submitting a referred website which should really be a search engine.  But unfortunately, I don't have the tech know-how to do it.  So if someone would be so kind?  The whole url:  https://www.bing.com/.

Other issue is symbaloo.com.  I'm not sure what to call it, but I think should probably be identified as a Direct Entry.  It looks like some kind of special homepage, for members.....like a favorite or bookmark.  Whole url:  http://www.symbaloo.com/home/mix/13ePBd7C0R

Thank you very much  :-)

**Comment by fvdm** [comment]
Bing is Microsoft's search engine. Referrer links from them should appear under Search Engines instead of Websites. At least that's how they are sorted in my Piwik.

**Comment by sgiehl** [comment]
Those urls are both no referrer spam.
Bing should already be identified as search engine, but I'll check if the recognition needs to be adjusted.
We won't count any entries through Symbaloo as direct entries, as they aren't direct, even it it is a service to store bookmarks...
