### ISSUE TITLE
Spam list suggestions

### ISSUE THREAD

**Issue by wencotex** [piwik/referrer-spam-blacklist#132]
The following spam referrers have plagued my website - most of them are not in your current list.

Cheers and keep up the good work!
Andi

sitedomain.de
domain2008.com
videos-for-your-business.com
pizza-tycoon.com
remotepccleaning.com
closetcasevintage.com
gateauchocolat.net
gventouris.gr
pimababy.de
adf.ly
itcouldbelikethis.com
capstonesacramento.com
windowcleaning.com
echlinconsulting.com
appta.co
bonjourdefrance.es
elevateind.com
buysell8.com
meyer-hentschel.net
executivesecurityplan.com
ginsengtea.net
angeluci.com
wundur.com
electropeasant.com
kelleherfineart.com
yasabes.com
drl-products.com
furina.de
kalkulatorykredytowe.pl
website-errors-scanner.com
blog.ambmediadesign.com
aosheng-tech.com
aurikulomedizin.com
nutrex.com
capsafood.com
hosting.axton.cz
312wright.com
kiconsult.de
wfiu.org
lasisblog.com
fairandugly.ch
couponsnews.ru
atemgym.com
laupeus.net
capsafood.com
schiffsreisen-blog.de
funbookco.com
dennis-aogo.de
healthfitnesscenters.com
sites.brightwhistle.com
andreasjanson.de
hiero.biz
diekartegefunden.net
jaavedkhatree.com.au
blog.ambmediadesign.com
a-a-bau.ch
hvd-store.com
justprofit.xyz
pizza-imperia.com
mebel-alait.ru
android-vsem.org
ledstudio.org
aviapanda.ru
game-mmorpg.net
bookmaker-bet.com
mazal-shop.ru
gk-atlant.info
zaimhelp.ru
avtomatoff.com
valkiria-tk.ru
site.fliphtml5.com
horoshieokna.com
igrobuy.com
cinemaenergy-hd.ru
burgerinmac.com.ua
dlskype.com
tecspb.ru
worldhistory.biz
allcredits.su
finstroy.net
forums-de.ubi.com
downloadsphotoshop.com
porno.weprik.ru
expertnaya-ocenka.ru
labplus.ru
valkiria-tk.ru
blogos.kz
carswithmuscles.com
atlant-auto.info
pornotwit.com
plohaya-kreditnaya-istoriya.ru
virtuallawer.com
softtor.com
cruiseraf.net
gta-top.ru
angeladorer.com
bimatoprost-careprost.com
netpics.org
gta-club.ru
vkontaktemusic.ru
expertnaya-ocenka.ru
komputers-best.ru
nardar.ru
jaxcube.info
lenvred.org
womensterritory.ru
nagdak.ru
realnye-otzyvy.info
play-euro-lotto.com
shoppingmiracles.co.uk
android4fun.org
wormix-cheats.ru
vostoktrade.info
ccpfy.net
dimkino.ru
simplepooltips.com
magda-gadalka.ru
favoritemoney.ru
infazavr.ru
recsil.org
ost-alpha.ru
sarafangel.ru
doeco.ru
bodybuilding-shop.biz
o-factory.ru
vekzdorov.ru
pornogig.com
xn--80ahvj9e.xn--p1ai
berlininsl.com
mir-business-24.ru
ublaze.ru
brendbutik.ru
luckyshop.net.ua
na15.ru

**Comment by mizzoni** [comment]
Thanks for flagging these!

**Comment by mattb77** [comment]
Yet another spammer:

http://www.igadgetsworld.com

Thanks for putting this together.

**Comment by spmedia** [comment]
Thanks for the update @mattb77 .

Can you please resubmit it as a pull request instead of an issue :)

<3
