### ISSUE TITLE
malaysia.search.yahoo.com

### ISSUE THREAD

**Issue by brynnd** [piwik/referrer-spam-blacklist#134]
HI Friends,
I've received a new referrer which appears to be a search engine.

malaysia.search.yahoo.com

There's an faq (or at least used to be) explaining what to do, to get it identified as a search engine, but I didn't understand it.  I'm not very tech-oriented.  Actually I'm surprised that the basic domain (yahoo.com) wasn't enough for it to be recognized as a search engine.  But that's a bit beyond my understanding as well.

So anyway, hopefully someone else can do whatever needs to be done.

Thank you very much  :-)

**Comment by sgiehl** [comment]
Thanks for your report. Even if this is the wrong repository to report this, I'll have a look and add it.
