### ISSUE TITLE
Dead domains (no DNS A record)

### ISSUE THREAD

**Issue by desbma** [piwik/referrer-spam-blacklist#135]
Some domains in the list are dead.
They have no DNS record and so can not be reached. A lot of others do not respond to ping, but they may be temporarily down or block ICMP, so I can not say for sure if they are dead.

Since the domains are dead, I doubt the spammers still send them as referer. They should probably be removed from the list.
It is also good to clean up the list, since the domains can change to a legitimate owner who does not use referer spam.

Dead domains:

```
alpharma.net
anal-acrobats.hol.es
blackhatworth.com
chinese-amezon.com
connectikastudio.com
edakgfvwql.ru
iloveitaly.ro
iloveitaly.ru
ilovevitaly.info
ilovevitaly.org
myftpupload.com
sexyteens.hol.es
slftsdybbg.ru
sohoindia.net
solnplast.ru
trafficmonetize.org
webmonetizer.net
ykecwqlixx.ru
грузоподъемные-машины.рф
наркомания.лечениенаркомании.com
непереводимая.рф
профмонтаж-врн.рф
снятьдомвсевастополе.рф
холодныйобзвон.рф
```

Note : I have a script to check the list and can do a pull request if it's easier for you.

**Comment by fvdm** [comment]
+1

**Comment by woaksie** [comment]
+1

**Comment by spmedia** [comment]
Wrong. 

грузоподъемные-машины.рф
наркомания.лечениенаркомании.com
непереводимая.рф
профмонтаж-врн.рф
снятьдомвсевастополе.рф
холодныйобзвон.рф

All still resolve and accessible.

**Comment by desbma** [comment]
Interesting.
I tried with 3 different DNS servers and got the same result.

    $ dig trafficmonetize.org

    ; <<>> DiG 9.9.5-3ubuntu0.5-Ubuntu <<>> trafficmonetize.org
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 30457
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ;; QUESTION SECTION:
    ;trafficmonetize.org.   IN  A

    ;; AUTHORITY SECTION:
    org.      1774  IN  SOA a0.org.afilias-nst.info. noc.afilias-nst.info. 2011759988 1800 900 604800 86400

    ;; Query time: 28 msec
    ;; SERVER: 127.0.1.1#53(127.0.1.1)
    ;; WHEN: Wed Nov 25 20:48:45 CET 2015
    ;; MSG SIZE  rcvd: 111

You may be seeing cached DNS entries that will soon expire. 
Which DNS server are you using?

**Comment by desbma** [comment]
https://www.whatsmydns.net/#A/trafficmonetize.org
http://downforeveryoneorjustme.com/trafficmonetize.org
https://www.dnswatch.info/dns/dnslookup?la=en&host=trafficmonetize.org&type=A&submit=Resolve

all tell me trafficmonetize.org is dead and gone

You are definitely querying through an outdated DNS cache.

**Comment by fvdm** [comment]
It seems only Comodo and UltraDNS are returning records.

[propagation](http://ceipam.eu/en/dnslookup.php?q=trafficmonetize.org&t=a&start=y&local=y&customdns=&Bellsouth=y&COMODO=y&EUROWEB=y&GTS=y&GOOGLE=y&HOSTNET=y&HurricaneElectric=y&LEVEL-3=y&Mindspring=y&NTT=y&OPENDNS=y&RDS=y&ROMTELECOM=y&Sprint=y&UltraDNS=y&UPC=y&VODAFONE=y)
[detail](http://d.pr/n/1ckF4)

**Comment by spmedia** [comment]
ayy:~ wat$ dig trafficmonetize.org

; <<>> DiG 9.8.3-P1 <<>> trafficmonetize.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25314
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;trafficmonetize.org.		IN	A

;; ANSWER SECTION:
trafficmonetize.org.	15	IN	A	92.242.140.2

;; Query time: 60 msec
;; SERVER: 10.0.1.1#53(10.0.1.1)
;; WHEN: Wed Nov 25 14:13:49 2015
;; MSG SIZE  rcvd: 53


Cox DNS servers

**Comment by desbma** [comment]
@spmedia no worry, you pointed out a valid issue ;-)

I have changed my script to cross check with several big, non filtering DNS servers, and to check ports 80/443 if DNS servers don't all agree.

The result are *almost* the same.

**Comment by mattab** [comment]
I suppose dead domains may come back as spammers. Maybe it's worth leaving them in the list?

**Comment by lembitk** [comment]
Well, yes, I suppose dead domains **could** come back… And while I personally would prefer a bit cleaner list, it's a valid argument. Thanks @mattab for taking a stand on this, I will close #227 as a result (and you might want to close this issue + #139).
