### ISSUE TITLE
sanjosestartups.com

### ISSUE THREAD

**Issue by brodjustice** [piwik/referrer-spam-blacklist#14]
This one points to an Alibaba site

**Comment by mnapoli** [comment]
Is it a referrer spammer? Where did you see it appear?

**Comment by hakunin** [comment]
Since it points to alibaba, it must have been expired domain bought for spam purpouses.

**Comment by brodjustice** [comment]
Appeared in Google Analytics -> Acquisition -> Referrals.  Over 50% of the website traffic came from there. I suppose it could be part of an ad campaign, but why not have Alibaba as the referer rather than sanjosestartups.com. Who is data looks suspicious:

http://mxtoolbox.com/SuperTool.aspx?action=mx%3asanjosestartups.com&run=toolpage#

**Comment by hakunin** [comment]
Whois says its registered by russian guy, definitely spam.

**Comment by hakunin** [comment]
Googling the guy who owns that domain:
https://www.google.cz/search?q=Vitaly+Popov&oq=Vitaly+Popov&aqs=chrome..69i57.387j0j4&sourceid=chrome&es_sm=91&ie=UTF-8

**Comment by mnapoli** [comment]
Yes looks like it should make it to the spammer list indeed.
