### ISSUE TITLE
buttons-for-your-website.com shows up

### ISSUE THREAD

**Issue by curiouscat** [piwik/referrer-spam-blacklist#18]
buttons-for-your-website.com shows up in my referer list.

so does best-seo-offer.com

http://piwik.org/blog/2015/05/stopping-referrer-spam/  even has buttons-for-your-website.com as an example of what is automatically blocked by piwik.  But it shows up for me?

I'm not sure if this is where I am suppose to post something like this?

**Comment by mnapoli** [comment]
Hi @curiouscat 

> I'm not sure if this is where I am suppose to post something like this?

Not really here but it's fine ;) You should update to the latest version if you want to benefit from the spam filtering in Piwik (my guess is that you are not on 2.13.1).

If you need help, you can ask in the forums (http://forum.piwik.org/list.php?2) or if it's a bug in Piwik (e.g. if you are on the latest version of Piwik) then you can open a bug here: https://github.com/piwik/piwik/issues

My other guess if you are using Piwik 2.13.1 is that the spammers list bundled with this version was the first version and didn't contain `buttons-for-your-website.com` and others. Those spammers will be filtered in the next version (2.14.0).

**Comment by curiouscat** [comment]
Thanks, just so you know I am using 2.13.1 - I'll see what happens with 2.14.0 and thanks for the forum link.
