### ISSUE TITLE
New referrer spam from top1-seo-service.com 

### ISSUE THREAD

**Issue by rlizzi** [piwik/referrer-spam-blacklist#206]
Hit 4 times in 24 hours by top1-seo-service.com.  In all cases, when I hover over the link in the Visitor Log, I see something like this:  http://top1-seo-service.com/try.php?u=http://longriverpublishing.com

I'm not sure if this is significant, but my website is at gooutsidebook.com.  The domain name at the end of the link is another one that I own that points to gooutsidebook.com.  I've seen two referrals with that other domain I own and two more from another domain I own.

**Comment by appeltauer** [comment]
+1 in few accounts

**Comment by rlizzi** [comment]
Not sure the previous comment means, but maybe it's not for me.

I should add that I included top1-seo-service.com to my .htaccess file after I saw the first hit, but it did not prevent subsequent hits.

**Comment by mnapoli** [comment]
I've added it manually, thank you.
