### ISSUE TITLE
Allow manual update within Piwik admin

### ISSUE THREAD

**Issue by tholu** [piwik/referrer-spam-blacklist#213]
It would be great to have a button in admin to manually update this list in Piwik admin, to make sure to have the latest version.

**Comment by mnapoli** [comment]
Hi, please open an issues at https://github.com/piwik/piwik since it would need to be implemented in that project.

**Comment by tholu** [comment]
Ok, opened the issue here: https://github.com/piwik/piwik/issues/9380
