### ISSUE TITLE
add *.copyrightclaims.org

### ISSUE THREAD

**Issue by sureshdsk** [piwik/referrer-spam-blacklist#222]
Got referral spam subdomains of copyrightclaims.org

**Comment by spmedia** [comment]
+1

**Comment by appeltauer** [comment]
Guys, copyrightclaims.org is already on the list...

**Comment by mnapoli** [comment]
Indeed (https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt#L79), thanks @appeltauer.
