### ISSUE TITLE
Some domains not blocked correct.

### ISSUE THREAD

**Issue by skywriter-a** [piwik/referrer-spam-blacklist#23]
Dear colleagues,
i have issues with these domains:
1) www2.free-social-buttons.com
2) www3.free-social-buttons.com
3) www8.free-social-buttons.com
I use Referrer Spam Blocker plugin for WordPress by Tomasz Tybulewicz. But these three domains they are still present in the list of referrals google analitycs.
Do you have any ideas about this?
Thank you for your assistance.

**Comment by mattab** [comment]
Hi there,

Please use Piwik if you want to have Spammer websites excluded from the reports: http://piwik.org/

Learn more: https://piwik.org/blog/2015/05/stopping-referrer-spam/
