### ISSUE TITLE
Add 2your.site

### ISSUE THREAD

**Issue by Venicei** [piwik/referrer-spam-blacklist#240]
Please add the following to your list. As a non-tech person, I couldn't figure out how to add it to the pull list.

website-stealer-warning.hdmoviecamera.net
w3javascript.com
claim70831006.copyrightclaims.org
website-stealer.nufaq.com
topseoservices.co
build-a-better-business.2your.site
new-look.for-your.website
trafficgenius.xyz
build-audience.for-your.website
smarter-content.for-your.website

Thanks
Katia

**Comment by mnapoli** [comment]
Thank you Katia, after checking only `2your.site` is not already in the list. I will rename the issue accordingly to help searching.

**Comment by Venicei** [comment]
Thanks. Do you know why they still showed up after I installed the plugin? I thought it updated automatically. Should I do something else?

Best regards
Katia

**Comment by appeltauer** [comment]
+1 2your.site

**Comment by lembitk** [comment]
+1 2your.site

**Comment by mnapoli** [comment]
Thanks.

**Comment by HelgeSverre** [comment]
+1 2your.site
