### ISSUE TITLE
Add с.новым.годом.рф

### ISSUE THREAD

**Issue by Venicei** [piwik/referrer-spam-blacklist#244]
thanks
Katia

**Comment by appeltauer** [comment]
+1

**Comment by annban** [comment]
+1

**Comment by spmedia** [comment]
I submitted this one already iirc

**Comment by mnapoli** [comment]
@spmedia Indeed it seems to be the last entry: https://github.com/piwik/referrer-spam-blacklist/blob/85db74cfc7249cb34ff59eba22edeb6704fd69b8/spammers.txt#L329
