### ISSUE TITLE
Add inspsearch.com

### ISSUE THREAD

**Issue by mtbsomi** [piwik/referrer-spam-blacklist#249]
Have .hu domain, hungarian languaged for .hu users.

Even not working website at inspsearch.com.

**Comment by appeltauer** [comment]
inspsearch.com works on multiple subdomains and according to my data it looks as real search engine...
viview.inspsearch.com
govome.inspsearch.com
kingtale3.inspsearch.com
airzip.inspsearch.com

Not really sure if we should exclude this.

**Comment by mtbsomi** [comment]
I've just checked the main domain but you're right. Sorry for opening the issue :)
