### ISSUE TITLE
New Spam?

### ISSUE THREAD

**Issue by arelidev** [piwik/referrer-spam-blacklist#255]
I'm not 100% sure if this is spam as it's a real site, but I've been seeing and don't have any ties to it: issuu.com

**Comment by spmedia** [comment]
It's a real site/legit, does not engage in referrer spam.

**Comment by mnapoli** [comment]
It doesn't *look* like all the other spammer websites at least.

**Comment by spmedia** [comment]
It's a popular website in the press release/SEO/content community.

If I had to guess, someone published an article/PDF with The Areli Group
URL on it and they are seeing traffic from that.

**Comment by mnapoli** [comment]
:+1: thanks for the info, let's close this for now.
