### ISSUE TITLE
Delete cityadspix.com

### ISSUE THREAD

**Issue by KingDzu** [piwik/referrer-spam-blacklist#266]
I'm system administrator group companies Cityads Media [https://cityads.com]

Domain **cityadspix.com** is used exclusively as the domain redirects to the customers. He did not use to send spam.

Please, delete this domain from the spam list.

**Comment by spmedia** [comment]
Eh, seems a lot of other people complain about your domain + referrer spam as well...

https://www.google.com/search?q=cityadspix.com+spam

IMO it should stay

**Comment by mattab** [comment]
@KingDzu as @spmedia mentions, it looks like your domain is used for spam. if you have some explanation please let us know :+1:
