### ISSUE TITLE
Firefox not reporting live users

### ISSUE THREAD

**Issue by cjerrington** [piwik/referrer-spam-blacklist#268]
I was curious about this project and decided to try it out. One way to make sure my Google Analytics work is to look at the live mode. Firebox sometimes, but not always reported a live user. I was able to see the live user using Google Crome and Windows new browser Edge? 

Does anyone else notice this?

**Comment by mnapoli** [comment]
I think you confused this repository with another one, this one is about blacklisting spammer domains.

**Comment by cjerrington** [comment]
No I am not confused. It is how the Google Analytics are referenced in the IF statement seems to slow down the response time of reporting actual results back to Google.

**Comment by mnapoli** [comment]
I genuinely do not understand what you are talking about. There is no IF statement in this repository, there is no code: this is a textual list of domains (https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt).

**Comment by cjerrington** [comment]
Hmm I guess what I was asking was using this spammers.txt in this repository: https://github.com/MohamedBassem/spam-referrals-blocker#how-it-works

I can redirect my question there.

**Comment by mnapoli** [comment]
:+1: This project is really interesting by the way thanks for sharing!
