### ISSUE TITLE
How does this apply to Apache hosted Piwik?

### ISSUE THREAD

**Issue by highacid** [piwik/referrer-spam-blacklist#270]
This is not a bug more like a question, how can I apply this into a Piwik running on apache? Thanks in advance.

Regards,
Cosmin

**Comment by quba** [comment]
You don't have to do anything. It should work out of the box.

**Comment by mnapoli** [comment]
:+1:

**Comment by highacid** [comment]
Still I do not get it how does one installs it on apache...

**Comment by spmedia** [comment]
You just install piwik. The spam blacklist is prebuilt into it.

**Comment by highacid** [comment]
@spmedia perfect, thanks for clarifying this.
