### ISSUE TITLE
What happed to the spammers? Did Google do something?

### ISSUE THREAD

**Issue by brodjustice** [piwik/referrer-spam-blacklist#273]
Apologies in advance as this may not be the correct place for this question, but I'm not sure where else to post this:

Has Google done something to stop referrer spammers? In the past 2 or so weeks all, I and I do mean all, referrer spammers have disappeared from all of our our websites. This should be good news I know, but we're a little spooked by this. Are we alone in seeing this?

Thanks!

**Comment by appeltauer** [comment]
Yes, Bot filtering feature (in Google Analytics View settings) now filters SPAMmers quite well.

Kind Regards,
Roman Appeltauer
Founder DIGMATO.com
+420 720 758 983

**Comment by spmedia** [comment]
I have a few GA accounts that don't have the bot filtering feature enabled and still seeing way less referrer spam. Google definitely updated/changed something for the better! :)
