### ISSUE TITLE
Add responsive-test.net

### ISSUE THREAD

**Issue by lukdumi** [piwik/referrer-spam-blacklist#275]
I get something like this: 2480831.responsive-test.net 

This site is a kind of a tool that tests responsivness. A sort of mess for piwik users.
responsive-test.net redirects to http://youresponsive.com/

I'm not sure if it qualifies for the referrer spam though.

**Comment by mnapoli** [comment]
I don't think it qualifies as referrer spam indeed.

**Comment by lukdumi** [comment]
Well, then it would be great for the user to be able to exclude traffic from certain domains.
Maybe https://github.com/piwik/piwik/issues/3589 will solve the problem...

**Comment by mnapoli** [comment]
:+1: this would need to be implemented in Piwik indeed. Closing as this doesn't concern this repository directly.

**Comment by pymarco** [comment]
+1 please block

http://botcrawl.com/responsive-test-net-referral-spam-google-analytics/

https://www.ohow.co/what-is-responsive-test-net-referral-google-analytics/

**Comment by mnapoli** [comment]
Reopening then :)

**Comment by spmedia** [comment]
+1

**Comment by mnapoli** [comment]
Fixed in #281

**Comment by lukdumi** [comment]
Thanks :-)
