### ISSUE TITLE
Add free-video-tool.com

### ISSUE THREAD

**Issue by gdementen** [piwik/referrer-spam-blacklist#298]
Please also block free-video-tool.com ...

**Comment by mnapoli** [comment]
Thank you but it's already on the list.

**Comment by gdementen** [comment]
Oups, sorry for the noise, #295 indeed. I just got spammed and I am running the latest piwik and didn't see it in open issues, so I just assumed it wasn't reported yet, you are just too quick at applying PR ;-)...

**Comment by mnapoli** [comment]
;) no problem
