### ISSUE TITLE
Putting a stop to the 'Cookie Law' domain referrer spam wave

### ISSUE THREAD

**Issue by spmedia** [piwik/referrer-spam-blacklist#354]
Can we agree to just generate and add all **cookie-law-enforcement-XX.xyz** variations ?

XX being aa thru zz.

GoDaddy is currently offering a sale of $0.99 on all .xyz domains so we're going to see a large uptick in .xyz referrer spam in general IMO. https://www.godaddy.com/tlds/xyz-domain . All of these cookie-law domains are registered with 1and1.com which also has the same $1 .xyz domain deal going on.

Here is the full list of all 26 variations http://pastebin.com/aReteJqd

It appears domains aa-jj have been registered so far. Domains kk-zz have not been registered as of 6/2/16.

Cheers

**Comment by mnapoli** [comment]
I'm perfectly fine with this! 👍

**Comment by mnapoli** [comment]
I'm holding off merging PRs about these domains in the meantime

**Comment by spmedia** [comment]
Alright, let's add all cookie URLs from list!

http://pastebin.com/aReteJqd

**Comment by mnapoli** [comment]
Done thanks!
