### ISSUE TITLE
Alphabetical sorting.

### ISSUE THREAD

**Issue by Zegnat** [piwik/referrer-spam-blacklist#36]
What algorithm is used for the alphabetical sorting? `sort spammers.txt` on Mac OS X has a couple of differences from the spammers.txt here in the repository.

**Comment by mnapoli** [comment]
For now it's sorted manually. Is the order different for non-latin characters? or something else?

**Comment by Zegnat** [comment]
The all cyrillic domains stay at the end, it is mostly how punctuation is sorted. `-` and `.` go before characters, so `ci.ua` goes before `cityadspix.com`. It is not really a big deal, but it means that [an easy to do `sort`](https://github.com/piwik/referrer-spam-blacklist/pull/13#issuecomment-109216490) before creating a PR shows unnecessary changes in the `diff`.

**Comment by mnapoli** [comment]
I agree it's better to rely on something automated and standard. If you wish to create a pull request feel free.

**Comment by mattab** [comment]
I suggest we use unix `sort` tool to sort the file. That's what I used when last sorting it.
