### ISSUE TITLE
webmonetizer.net

### ISSUE THREAD

**Issue by brodjustice** [piwik/referrer-spam-blacklist#42]
According to the new 'peer review process' I'll add here as an issue rather than a pull-request and wait for a +1

webmonetizer.net - turned up few last week and over 3 days and caused 34 sessions with 100% bounce rate. Left it's mark in the Google analytics Aquisition -> All Traffic -> Referrals table. Cities of origin all Russian (Chelyabinsk, Krasnoyarsk, Volgodonsk, Yekaterinburg, etc.). The domain itself redirects to Adzos -> getyourprofit.net. Domain is registared in Nobby Beach, Queensland, Australia just like some other other referral spam domains.

**Comment by mattab** [comment]
added in https://github.com/piwik/referrer-spam-blacklist/commit/08ef242b2fcbe165dff7d80b0b3c5671ebf84b6d

**Comment by mattab** [comment]
Hi @brodjustice in the future feel free to issue Pull Requests, and other users can `+1` in the pull request (it saves a bit of time VS first creating an issue, then a pull request)

**Comment by mnapoli** [comment]
@mattab:

> According to the new 'peer review process' I'll add here as an issue rather than a pull-request and wait for a +1
