### ISSUE TITLE
how to integrate into PIWIK

### ISSUE THREAD

**Issue by tbba** [piwik/referrer-spam-blacklist#44]
Hi, can you give a brief description how to integrate this list into PIWIK best?
In this document it is written that PIWIK catches SPAM automatically, using info from this repo:
http://piwik.org/blog/2015/05/stopping-referrer-spam/

But I have currently spam turning up in PIWK, that I found listed on this list already (100dollar-seo, semaltmedia), so obviously something isn't working as expected here.

**Comment by Globulopolis** [comment]
@tbba read this thread http://forum.piwik.org/read.php?3,127430,127498
I think it's better to handle spammers at server side not on Piwik.

**Comment by mnapoli** [comment]
Hi, @tbba please see this comment which answers your question: https://github.com/piwik/referrer-spam-blacklist/issues/35#issuecomment-111621027

@Globulopolis if you only block access to your website, spammers can still spam your Piwik directly (without going through your website). You can however set up your webserver to block spammer requests coming directly to Piwik, however it's much easier to let Piwik do the job.

**Comment by tbba** [comment]
Auto update in PIWIK sounds exacly as what I want. 
Since I am No.2 already (sorry, I forgot to look at the closed issues for more info first) with the same question, may I consider a short note in your documentation that this repo is for updating the list only - and that PIWIK will use the list automatically and no manual action from the PIWIK user is required?

**Comment by mnapoli** [comment]
Yes feel free to submit a pull request
