### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mnapoli** [piwik/referrer-spam-blacklist#505]
@spmedia would you consider becoming a maintainer of this project? @mattab would you be open to grant him these permissions?

@spmedia has been [involved a lot](https://github.com/piwik/referrer-spam-blacklist/graphs/contributors) lately and we need one more person to merge the pull requests, the amount of notifications is a bit high for me to follow everything.

**Comment by spmedia** [comment]
I'm gladly open to help.

**Comment by mattab** [comment]
Hi @mnapoli Great idea! The more of us the merrier. 

Hi @spmedia: Welcome to our Referrer Spam repository! you now have write access to the repo. We are grateful for your help and hope to continue building together the most comprehensive Referrer Spammer list on the web.

**Comment by mattab** [comment]
if other people are actively contributing and wish to be part of the maintainers, please let me know here, and we will consider it for sure :+1:
