### ISSUE TITLE
www.igadgetsworld.com

### ISSUE THREAD

**Issue by mattb77** [piwik/referrer-spam-blacklist#529]
I've been getting homepage requests from this in a wordpress site for 4 months.

**Comment by mattb77** [comment]
Not able to commit spammers.txt to master. Do I need to create a new branch?

**Comment by spmedia** [comment]
@mattb77 , goto https://github.com/piwik/referrer-spam-blacklist/pulls

and then click the "New Pull Request" button and post this there. This is still the issues tab :)

**Comment by mattb77** [comment]
Please can someone update the instructions. It says comment on any issue or do a pull request. I could only do a pull request by 1) creating a fork 2) downloading the fork 3) making the change locally, then 4) committing back to fork and then 5) creating the pull request. Not everyone will know these steps if they don't do much collaborative development and I needed explanation by Farhan here http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request

**Comment by mattab** [comment]
@mattb77 creating a pull request is much easier, see: https://github.com/blog/1738-web-flow-editing-from-pull-requests i'll update instructions

**Comment by mattab** [comment]
Actually instructions are already quite clear so couldn't really make them better?! https://github.com/piwik/referrer-spam-blacklist/commit/13f6a020e59bca38605240719be97e85ef1644c1
