### ISSUE TITLE
Add spammers

### ISSUE THREAD

**Issue by Yannick001** [piwik/referrer-spam-blacklist#545]
892731605.keywordblocks.com
mystart3.dealwifi.com
free-social-buttons2.xyz
free-social-buttons3.xyz
free-social-buttons6.xyz
tklnk.com
free-social-buttons-fff.xyz
law-enforcement-check-one.xyz
bugof.gq
compliance-alex.top
compliance-barak.top
compliance-george.top
compliance-jack.top
compliance-jane.top
compliance-jess.top
compliance-jessica.top
compliance-john.top
compliance-viktor.top
compliance-walter.top
familyholiday.ml
gq-catalog.gq
homemade.gq
pinkduck.ga
lifehacker.com
thenextweb.com

**Comment by spmedia** [comment]
You need to submit these as Pull Requests(Instead of an issue) and please put each domain as it's own one so users can vote on them.

Thank you.
