### ISSUE TITLE
Punycode domains

### ISSUE THREAD

**Issue by BBcan177** [piwik/referrer-spam-blacklist#597]
Would you consider posting the punycode version of these domains?

(Domains redacted with a slash)

годом\\.рф
грузоподъемные-машины\\.рф
лечениенаркомании\\.com
непереводимая\\.рф
профмонтаж-врн\\.рф
снятьдомвсевастополе\\.рф
холодныйобзвон\\.рф

xn--\c1acygb.xn--p1ai
xn----\8sbhefaln6acifdaon5c6f4axh.xn--p1ai
xn--\80aanaardaperhcem4a6i.com
xn--\80adgcaax6acohn6r.xn--p1ai
xn----\7sbho2agebbhlivy.xn--p1ai
xn--\80adaggc5bdhlfamsfdij4p7b.xn--p1ai
xn--\90acenikpebbdd4f6d.xn--p1ai

via - https://www.punycoder.com/

**Comment by BBcan177** [comment]
#598 PR submitted

**Comment by istana** [comment]
what is the reason behind converting domain names to punycode format?

**Comment by BBcan177** [comment]
Most Host based feeds (>99%), use punycodes instead of IDN (Unicode) domains. Using the ASCII version of the domains is more appropriate for scripting, ie: Deduplication, whitelisting, searching etc... Also if one feed lists the IDN version, and another lists the Punycode version, there will be two different lines in the Hosts blocking file which can confuse the user.... So overall, its best to not use IDN domains as its not the most popular method to list domains.

**Comment by spmedia** [comment]
Done!
