### ISSUE TITLE
http://success-seo.com/try.php?u=http://<my-url>

### ISSUE THREAD

**Issue by andreasernst** [piwik/referrer-spam-blacklist#60]
redirect to http://semalt.com/

**Comment by hobgoblinsmaster** [comment]
just seen it also.

**Comment by micheleb** [comment]
+1 for success-seo.com

**Comment by micressor** [comment]
+1 for success-seo.com

**Comment by rolandinsh** [comment]
+1 success-seo.com

**Comment by bmustata** [comment]
+1 success-seo.com

**Comment by mattab** [comment]
Thanks for submission, added in https://github.com/piwik/referrer-spam-blacklist/commit/357c9411d2ff199458c78f619cd36024d0bdfe3d
