### ISSUE TITLE
www.foxweber.com

### ISSUE THREAD

**Issue by viktorix** [piwik/referrer-spam-blacklist#605]
Another site promoting traffic, showing up as a referring website with 2 visits for homepage. Here's a screenshot.
![ccd0yitxjp](https://user-images.githubusercontent.com/1692600/26921757-fec9a3cc-4c0a-11e7-8078-edc9af423f25.png)

**Comment by spmedia** [comment]
Thanks @viktorix 

Would you mind making a pull request for this as it is not an issue. Please add foxweber.com to the spammers.txt.

Thank you
