### ISSUE TITLE
Remove old referrer spam from database

### ISSUE THREAD

**Issue by manyk** [piwik/referrer-spam-blacklist#64]
Does anyone know if it's possible to remove the old spam referrers from database? For busy sites the spammers could alter the statistics excessively.

**Comment by Qlimax90** [comment]
That would be interesting for me to, as you can see after upgrading to 2.14.0 and regenerating all the reports via the shell, the known spam referrers still get listed: 
![unbenannt](https://cloud.githubusercontent.com/assets/8558396/8589334/6177f640-2615-11e5-86ec-75054eda767c.png)

**Comment by danbruegge** [comment]
I have also 2 sites on "Referrer Websites" which are listed in the spammer.txt.

**Comment by mnapoli** [comment]
Sorry for the late answer. Piwik does not offer this feature as of today. Since this project is only about the blacklist, could you open an issue in Piwik's main repository: https://github.com/piwik/piwik/issues

Thank you
