### ISSUE TITLE
Helpful Google Analytics custom report for spambot hunting

### ISSUE THREAD

**Issue by chrisblakley** [piwik/referrer-spam-blacklist#69]
I've shared a custom report template for Google Analytics that has immensely helped discover referral spambot domains (and hostnames they use).

https://www.google.com/analytics/web/template?uid=MEsjTogmTgWfOeeYm-Liyg

I've been keeping [my own gist](https://gist.github.com/chrisblakley/e31a07380131e726d4b5) for spambot blacklisting, but now that I've discovered this repo it looks like I'll probably start contributing here instead.

**Comment by lembitk** [comment]
Thanks Chris, very useful indeed.

I feel I get slightly better filtering by switching the "Exclude Hostname" filter from "exact" to => "regex" and adding a pattern including `googleusercontent.com` + 3rd party service domains appropriate for the view(s) selected.
