### ISSUE TITLE
WordPress plugin

### ISSUE THREAD

**Issue by rolandinsh** [piwik/referrer-spam-blacklist#78]
Just made WordPress plugin for this list. 

GitHub version : https://github.com/rolandinsh/wp_referrer_spam_blacklist 
WordPress.org: https://wordpress.org/plugins/wp-referrer-spam-blacklist/

**Comment by mattab** [comment]
:+1:

**Comment by rrodrigonuez** [comment]
That's something too similar what already exists...
https://wordpress.org/plugins/wp-block-referrer-spam

**Comment by rolandinsh** [comment]
Yes, yesterday found  that too, but You have different approach ;)
I see both were accepted almost same time from WordPress. https://wordpress.org/plugins/wp-referrer-spam-blacklist/ I'll try to keep as simple as possible, but still managed way.

**Comment by rrodrigonuez** [comment]
GOOD!

**Comment by kwielo** [comment]
I have also created one:
https://wordpress.org/plugins/stop-referrer-spam/
Mine is really simple ;)

**Comment by spmedia** [comment]
Is absolutely the best for Google Analytics

http://gaspamfighter.com/

**Comment by appeltauer** [comment]
@spmedia The most important feature is auto update. So the best for me is DIGMATO. ;-)
https://digmato.com/google-analytics/referral-spam-filter-buy

**Comment by rolandinsh** [comment]
FYI: autoupdate is considered as security hole :)
