### ISSUE TITLE
Add documentation for banning via Apache

### ISSUE THREAD

**Issue by mattkolb** [piwik/referrer-spam-blacklist#80]
This probably would have been better via a pull request, but I'm not exactly use to using GitHub. I really like the list and update frequency you guys have going. We use Piwik on a regular basis, but we also wanted to stop wasting server resources on serving the requests as well. I thought the info might be useful to others.

---

The info below shows how configure Apache to redirect the requests back to the referring site to avoid wasting your server resources serving the requests. Alternatively, you could simply make the requests fail. 

In your httpd.conf, add the following to each VirtualHost:

```
<VirtualHost *:80>
....
RewriteMap    ref-deny  txt:/PATH/TO/spammers.map

# two part domains in file, possible subdomain in request
RewriteCond %{HTTP_REFERER} !=""
RewriteCond %{HTTP_REFERER} ://(?:[^/]*\.)?([^\./]+\.[^\./]+)(/|$)
RewriteCond ${ref-deny:%1|NOT-FOUND} !=NOT-FOUND [NC]
RewriteRule .* %{HTTP_REFERER} [R,L]

# three part domains in file, possible subdomain in request
RewriteCond %{HTTP_REFERER} !=""
RewriteCond %{HTTP_REFERER} ://(?:[^/]*\.)?([^\./]+\.[^\./]+\.[^\./]+)(/|$)
RewriteCond ${ref-deny:%1|NOT-FOUND} !=NOT-FOUND [NC]
RewriteRule .* %{HTTP_REFERER} [R,L]
...
</VirtualHost>
```

Be sure to set the appropriate path to spammers.map which will be created below.

If you would prefer to have the request simply fail instead of redirecting back to the page that is creating the referer spam, simply replace [R,L] with [F] in the two lines above.

Next, you need to create spammers.map from spammers.txt. Just make sure to have a space and hyphen on each line after the domain. Here's an example:

```
semalt.com -
buttons-for-your-website.com -
success-seo.com -
```

Save the config files and restart Apache.

**Comment by mattkolb** [comment]
If you are trying to test the above, the extension below is fairly handy so that you can quickly run through a bunch of test cases:
https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin?utm_source=chrome-app-launcher-info-dialog

**Comment by phillipcavaco** [comment]
RewriteEngine on
Double check if RewriteEngine is on

**Comment by futureweb** [comment]
As mod_rewrite is much more performance intense than mod_setenvif i prefer this approach:

> \<IfModule mod_setenvif.c>
>      SetEnvIfNoCase Referer 0n-line.tv spambot=yes
>      SetEnvIfNoCase Referer 100dollars-seo.com spambot=yes
>      ...
>      ...
>      ...
>      Order allow,deny
>      Allow from all
>      Deny from env=spambot
> \</IfModule>

In my case I create a file from this List with PHP (with sanity checks in case this List gets corrupted...) and include it within httpd.conf

> \<Directory "/var/www/html">
>   #include Referer Spam Blocks
>   Include /var/www/html/includes/.htaccessSpammersInclude
> \</Directory>

Just my 5 Cents on this Topic! ;-)

Andreas Schnederle-Wagner

**Comment by IzzySoft** [comment]
With Apache and `mod_security`, simply download the file and use a single line of config:

```apache
SecRule REQUEST_HEADERS:REFERER "@pmFromFile spammers.txt" "deny,log,noauditlog,ctl:auditEngine=Off,severity:2,msg:'Referer spammer blocked',status:403,id:60001"
```

(this assumes the file is located in the same directory as the config file the line is added to)
