### ISSUE TITLE
How often does Piwik fetch this list?

### ISSUE THREAD

**Issue by dandv** [piwik/referrer-spam-blacklist#83]
I'd like to see in the README something about the frequency with which Piwik download the latest version of this list. I still see some domains that have been submitted since July 2 or ealier:

![image](https://cloud.githubusercontent.com/assets/33569/8746009/043af4a2-2c3a-11e5-8f13-3ff6911551eb.png)

Also, if a domain is on the list but Piwik logged visits from before it was on the list, will all visits be cleared, or only the ones after the new version of the list was updated?

**Comment by micressor** [comment]
+1

**Comment by sgiehl** [comment]
It should be updated within a weekly task. But maybe there is a cache clear missing after the update. Try clearing the cache using the console or clean the piwik tmp directory.

**Comment by mnapoli** [comment]
It is updated [weekly](https://github.com/piwik/piwik/blob/master/plugins/CoreAdminHome/Tasks.php#L51).

I have added more information in the readme in 74020421728da48a6864a7d221de5a395a10659d
