### ISSUE TITLE
www.acunetix-referrer.com

### ISSUE THREAD

**Issue by manyk** [piwik/referrer-spam-blacklist#84]
I see this is new. Does anyone know more about this referrer?
It looks it hit my server this morning, complete website, all the pages in under 15 minutes.

![acunetix screenshot - 20_07](https://cloud.githubusercontent.com/assets/5571905/8781898/9eef8ad4-2f1a-11e5-94fd-91c277b7d893.jpg)

**Comment by lembitk** [comment]
+1

**Comment by ea4fvb** [comment]
we had the same thing, but from different ips in different countries is a web attack
